### PR TITLE
Add about and FAQ page

### PR DESCRIPTION
**Pull request by narrator0**
See https://github.com/LibreTexts/jupyterhub-images/pull/1 for details.

### CODE REVIEW

**Comment by moorepants** [comment]
Are these now ready?

**Comment by narrator0** [comment]
This is ready but I would like to merge it when all relevant PRs are ready.

**Comment by moorepants** [comment]
So what are the PRs and what order do they need to be merged?

**Comment by narrator0** [comment]
Waiting for LibreTexts/jupyterhub-images#1.

**Pull request merged**
