### PR TITLE
Adding Google Analytics

### PR DESCRIPTION
**Pull request by TimStewartJ**
This would add Google Analytics tracking to our JupyterHub. Currently the tracking tag is in all pages except for the actual JupyterLab itself. The FAQ rendering script would have to be re-run after merging.

Relevant to https://github.com/LibreTexts/metalc/issues/196.

### CODE REVIEW

**Comment by moorepants** [comment]
Who's google analytics account is it pointed to? I think this would need to be point to Delmar's account if it isn't.

**Comment by TimStewartJ** [comment]
Currently it's pointed to libretextsteam@gmail.com, I'm not sure what Delmar's account is.

**Comment by moorepants** [comment]
Delmar operates a google analytics account for the libretexts website. The request from Delmar is that he be able to track usage on jupyter.libretexts.org and binder.libretexts.org from *his* account.. He should issued a google analytics code for us to embed here, so that he's tracking things, not us.

**Comment by TimStewartJ** [comment]
Alright, I'll get in contact with him and get the codes updated in that case.

**Comment by moorepants** [comment]
Great!

**Comment by TimStewartJ** [comment]
Alright, the pages have been updated with the code for tracking for Delmar now.

**Pull request merged**
